# Scrape daily
name: Scrape

on:
  schedule:
    - cron: "*/2 * * * *"

jobs:
  scrape:
    runs-on: macos-latest

    steps:

      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v1
      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages: |
            devtools
      - name: test
        run: |
          Rscript -e 'devtools::install_github("vohai611/gsovn")'
          Rscript -e 'gsovn::gso_avail()'

